[project]
name = "khadijarecipes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0a1",
    "ipdb>=0.13.13",
    "pyclean>=3.1.0",
]
