# Generated by Django 6.0a1 on 2025-10-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_de", models.CharField(max_length=256)),
                (
                    "question_en",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "question_fr",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "question_es",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "question_it",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("answer_de", models.TextField()),
                ("answer_en", models.TextField(blank=True, null=True)),
                ("answer_fr", models.TextField(blank=True, null=True)),
                ("answer_es", models.TextField(blank=True, null=True)),
                ("answer_it", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="DummyModel",
        ),
    ]
