# Generated by Django 6.0a1 on 2025-10-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_de", models.CharField(max_length=256)),
                ("title_en", models.CharField(blank=True, max_length=256, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=256, null=True)),
                ("title_es", models.CharField(blank=True, max_length=256, null=True)),
                ("title_it", models.CharField(blank=True, max_length=256, null=True)),
                ("slug_de", models.SlugField(max_length=256)),
                ("slug_en", models.SlugField(blank=True, max_length=256, null=True)),
                ("slug_fr", models.SlugField(blank=True, max_length=256, null=True)),
                ("slug_es", models.SlugField(blank=True, max_length=256, null=True)),
                ("slug_it", models.SlugField(blank=True, max_length=256, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
