# Generated by Django 6.0a1 on 2025-10-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_ingredient_unit_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeimage",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="recipenote",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="description_es",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="description_fr",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="description_it",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="amazon_affiliate",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cuisine",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="description_es",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="description_fr",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="description_it",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="meta_description_de",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="meta_description_en",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="meta_description_es",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="meta_description_fr",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="meta_description_it",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="promote_in_telegram",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="rest_time",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="notes_de",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="notes_en",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="notes_es",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="notes_fr",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="notes_it",
        ),
        migrations.RemoveField(
            model_name="recipestep",
            name="image",
        ),
        migrations.RemoveField(
            model_name="recipestep",
            name="timer_duration",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("appetizer", "Appetizer"),
                    ("main", "Main Course"),
                    ("dessert", "Dessert"),
                    ("snack", "Snack"),
                    ("beverage", "Beverage"),
                    ("bread", "Bread"),
                ],
                default="main",
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.DeleteModel(
            name="NutritionInfo",
        ),
        migrations.DeleteModel(
            name="RecipeImage",
        ),
        migrations.DeleteModel(
            name="RecipeNote",
        ),
    ]
