# Generated by Django 6.0a1 on 2025-10-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_remove_recipeimage_recipe_remove_recipenote_recipe_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="date_published",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="servings",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name_de",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name_es",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name_fr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name_it",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="introduction_de",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="introduction_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="introduction_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="introduction_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="introduction_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="instruction_de",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="instruction_en",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="instruction_es",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="instruction_fr",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="instruction_it",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="recipes.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name_de",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name_en",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name_es",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name_fr",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name_it",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
