# Generated by Django 6.0a1 on 2025-10-19 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_remove_recipe_date_published_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="unit_text",
        ),
    ]
