# Generated by Django 6.0a1 on 2025-10-19 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_remove_recipeingredient_unit_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "ordering": ["id"],
                "verbose_name": "Recipe Ingredient",
                "verbose_name_plural": "Recipe Ingredients",
            },
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="order",
        ),
    ]
