# Generated by Django 6.0a1 on 2025-10-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="recipes/ingredients/",
                verbose_name="Ingredients Image",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="prep_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="recipes/preparation/",
                verbose_name="Preparation Image",
            ),
        ),
    ]
