# Generated by Django 6.0a1 on 2025-10-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_recipe_ingredients_image_recipe_prep_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="name_plural_de",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="name_plural_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="name_plural_es",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="name_plural_fr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="name_plural_it",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="name_plural_de",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unit",
            name="name_plural_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="name_plural_es",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="name_plural_fr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="name_plural_it",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
