# Generated by Django 6.0a1 on 2025-10-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipes",
            "0008_ingredient_name_plural_de_ingredient_name_plural_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name_de",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name_de",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
