# Generated by Django 6.0a1 on 2025-10-18 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_img_de",
            new_name="alt_de",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_img_en",
            new_name="alt_en",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_img_es",
            new_name="alt_es",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_img_fr",
            new_name="alt_fr",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_img_it",
            new_name="alt_it",
        ),
    ]
