# Generated by Django 6.0a1 on 2025-10-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_alt_img_de_productimage_alt_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("mixed_pastries", "Mixed platters"),
                    ("sweet_pastries", "Sweet platters"),
                    ("honey_pastries", "Honey platters"),
                    ("cookies", "Cookies"),
                ],
                default="mixed_pastries",
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
