# Generated by Django 6.0a1 on 2025-10-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_200",
            field=models.ImageField(blank=True, null=True, upload_to="product-images/"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_400",
            field=models.ImageField(blank=True, null=True, upload_to="product-images/"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_800",
            field=models.ImageField(blank=True, null=True, upload_to="product-images/"),
        ),
    ]
