# Generated by Django 6.0a1 on 2025-10-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_productimage_image_200_productimage_image_400_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_600",
            field=models.ImageField(blank=True, null=True, upload_to="product-images/"),
        ),
    ]
