# Generated by Django 6.0a1 on 2025-10-23 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_price_1kg_product_price_500g_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price_price",
            new_name="price_per_unit",
        ),
    ]
