# Generated by Django 6.0a1 on 2025-10-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_rename_price_price_product_price_per_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_1kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Price 1kg",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_500g",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Price 500g",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Price per Unit",
            ),
        ),
    ]
