# Generated by Django 6.0b1 on 2025-10-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_product_price_1kg_alter_product_price_500g_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("mixed_pastries", "Mixed platters"),
                    ("sweet_pastries", "Sweet platters"),
                    ("honey_pastries", "Honey platters"),
                    ("cookies", "Cookies"),
                    ("dough_products", "Dough products"),
                ],
                max_length=32,
            ),
        ),
    ]
