# Generated by Django 6.0b1 on 2025-10-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_product_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("mixed_pastries", "Mixed platters"),
                    ("sweet_pastries", "Sweet platters"),
                    ("honey_pastries", "Honey platters"),
                    ("dough_products", "Dough products"),
                    ("cookies", "Cookies"),
                    ("other", "Other products"),
                ],
                max_length=32,
            ),
        ),
    ]
