# Generated by Django 6.0b1 on 2025-10-26 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_product_product_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_de",
            new_name="alt_text_de",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_en",
            new_name="alt_text_en",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_es",
            new_name="alt_text_es",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_fr",
            new_name="alt_text_fr",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="alt_it",
            new_name="alt_text_it",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="image_200",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="image_400",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="image_600",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="image_800",
        ),
    ]
